= SLF4J Binding to JBoss Logging

The https://www.slf4j.org/[SLFJ4J] binding to the JBoss Log Manager is just as it sounds. It's a
https://www.slf4j.org/manual.html#swapping[SLF4J binding] which sends log messages through the JBoss Log Manager. This
project is currently used in https://wildfly.org[WildFly] and
https://www.redhat.com/en/technologies/jboss-middleware/application-platform[JBoss EAP].

Currently, this supports both SLF4J 2.x and SLF4J 1.7.x. Support for 1.7.x is deprecated and will be removed in future
releases.

== Usage

To use the project you need both SLF4J and JBoss Log Manager on your class path. Then simply add this library and it should
be picked up as the SLF4J binding.

=== Maven
[source,xml]
----
<dependency>
    <groupId>org.jboss.slf4j</groupId>
    <artifactId>slf4j-jboss-logmanager</artifactId>
    <version>${version.org.jboss.logging.slf4j-jboss-logmanager}</version>
</dependency>
----

== Contributing

See the link:CONTRIBUTING.adoc[contributing guide].

== Releasing

Releasing this project requires access to https://repository.jboss.org/nexus[JBoss Nexus].

To perform a release ensure you're on the correct branch and that branch is up to date. Once done you can simply use
the `release.sh` bash script.

[source,bash]
----
./release.sh -r 2.0.2.Final -d 2.0.3.Final-SNAPSHOT
----

If this was successful, instructions will be printed on the console with the next set of instructions for processing.
