= SLF4J Binding to JBoss Logging

The https://www.slf4j.org/[SLFJ4J] binding to the JBoss Log Manager is just as it sounds. It's a
https://www.slf4j.org/manual.html#swapping[SLF4J binding] which sends log messages through the JBoss Log Manager. This
project is currently used in https://wildfly.org[WildFly] and
https://www.redhat.com/en/technologies/jboss-middleware/application-platform[JBoss EAP].

Currently, this supports both SLF4J 2.x and SLF4J 1.7.x. Support for 1.7.x is deprecated and will be removed in future
releases.

== Usage

To use the project you need both SLF4J and JBoss Log Manager on your class path. Then simply add this library and it should
be picked up as the SLF4J binding.

=== Maven
[source,xml]
----
<dependency>
    <groupId>org.jboss.slf4j</groupId>
    <artifactId>slf4j-jboss-logmanager</artifactId>
    <version>${version.org.jboss.logging.slf4j-jboss-logmanager}</version>
</dependency>
----

== Contributing

See the link:CONTRIBUTING.adoc[contributing guide].

== Releasing

Releasing the project requires permission to deploy to Maven Central see https://central.sonatype.org/publish/requirements/[Maven Central Release Requirements].
Once everything is setup, you simply need to run the `./release.sh` script. There are two required parameters:

1. `-r` or `--release` which is the version you want to release
2. `-d` or `--development` which is the next development version.

By default, the release version cannot contain `SNAPSHOT` and the development version, must contain `SNAPSHOT`.

[source,bash]
.Example Command
----
./release.sh -r 1.0.0.Final -d 1.0.1.Final-SNAPSHOT
----

=== Supported Arguments

|===
|Argument | Requires Value | Description

| `-d`, `--development`
| Yes
| The next version for the development cycle.

| `-f`, `--force`
| No
| Forces to allow a SNAPSHOT suffix in release version and not require one for the development version.

| `-h`, `--help`
| N/A
| Displays this help

| `--notes-start-tag`
| Unused
| Passes the `--notes-from-tag` and the argument to the `gh create release` command.

| `-p`, `--prerelease`
| Unused
| Passes the `--prerelease` to the `gh create release` command.

| `-r`, `--release`
| Yes
| The version to be released. Also used for the tag.

| `--dry-run`
| No
| Executes the release in as a dry-run. Nothing will be updated or pushed.

| `-v`, `--verbose`
| No
| Prints verbose output.

|===


Any additional arguments are considered arguments for the Maven command.
